### ISSUE TITLE
"Make a change" button has disappeared

### ISSUE THREAD

**Issue by Xyleneb** [SomethingNewUK/somethingnewuk.github.io#15]
People not familiar with github (myself included) were still able to use the "make a change" button on something new's website to contribute to the openpolitics manifesto, and with it gone, there may be other people who lack the computer literacy required in order to contribute.

**Comment by Floppy** [comment]
Oh, crikey, so it has. It should be on each page of the manifesto! I'll get it back on there as soon as possible, thanks for letting me know!

**Comment by Floppy** [comment]
Fixed now. It must have disappeared when I changed the layout files recently. Thanks for bringing it to my attention!

/me goes off to write some tests
