### ISSUE TITLE
Archive with Wayback Machine

### ISSUE THREAD

**Issue by philipjohn** [SomethingNewUK/somethingnewuk.github.io#9]
The Wayback Machine holds snapshots of websites but relies on its crawler. Inspired by [this WordPress plugin](https://wptavern.com/new-archiver-wordpress-plugin-auto-generates-wayback-machine-snapshots) I suggest we build into the website a ping to automatically update the Wayback Machine when it changes.

**Comment by Floppy** [comment]
I'll bet we can do that with a github hook...

**Comment by Floppy** [comment]
great idea also.

**Comment by Floppy** [comment]
Got this working just by adding https://web.archive.org/save/https://somethingnew.org.uk  to the github webhooks on page build. Amazing.

**Comment by Floppy** [comment]
Course, what I don't know is if that reindexes every page or just the one I told it to. Does it re-crawl?
